---
- name: install and start apache
  hosts: worker1

  tasks:
  - name: execute script
    shell: ./run.sh

  - name: change directory and then execute if no such file exists
    shell: ./run.sh
    args:
      chdir: sftp/
      creates: worker-node1

  - name: fetch file containing token
    shell:
      cmd: ls -l | grep token >> token 

