---
- name: Move configuration files and start master and slave JBOSS Servers
  hosts: XES1
  vars_files:
  - env_variables

  tasks:
  - name: Copy broker.xml
    copy:
      src: "{{ item }}"
      dest: "{{ Edifecs_Install_Dir }}/JBOSS/Slave/etc/broker.xml"
      mode: '0755'
      backup: yes
    with_items: 
      - conf/Slave/broker_s.xml

  - name: Copy jolokia.xml
    copy:
      src: "{{ item }}"
      dest: "{{ Edifecs_Install_Dir }}/JBOSS/Slave/etc"
      mode: '0755'
      backup: yes
    with_items:
      - conf/jolokia-access.xml

   
  - name: Editing bootstrap.xml to allow access for remote users"
    replace:
      dest: "{{ Edifecs_Install_Dir }}/JBOSS/Slave/etc/bootstrap.xml"
      regexp: 'localhost'
      replace: '0.0.0.0'
      backup: yes

  - name: Start slave jboss server
    shell: "source ~/.bash_profile &&  nohup ./artemis-service start  > nohup.out 2>&1 &"
    args:
      chdir: "{{ Edifecs_Install_Dir }}/JBOSS/Slave/bin"
